### ISSUE TITLE
Tx popup not showing the right amount when contributing to pool

### ISSUE THREAD

**Issue by dadeg** [Safehaven-io/ThorBlock#23]
The arkane transaction popup shows 0 vet as the amount, even though I typed 12 (11.94) in the form
but the actual tx that is visible on veforge shows the whole amount (https://testnet.veforge.com/transactions/0xcfca0e74a76412ed9ac65e627de2f69e5e1baced446a9397faf6a9dfb444eafa)
<img width="736" alt="screen shot 2018-10-22 at 9 39 42 am" src="https://user-images.githubusercontent.com/4580642/47300250-a5c04800-d5e1-11e8-9ba5-3b712fe03dec.png">

**Comment by JurgenSchouppe** [comment]
Should be ok now after new docker image deployment.
