### ISSUE TITLE
Show wallet name also in the create a pool screen

### ISSUE THREAD

**Issue by karelstriegel** [Safehaven-io/ThorBlock#26]
![image](https://user-images.githubusercontent.com/6882032/47367300-b6ef7e80-d6df-11e8-86d9-5c41fd9af4a0.png)

only address is visible, while users will related to their address using a name, not the hex string

**Comment by wijzijnwolf** [comment]
Fixed,
Converted to dropdown select. Loads in wallet data after page load using arkaneconnect.
Copy to clipboard button will still copy the hex-address of currently selected wallet.
Same for external link.
