### ISSUE TITLE
When funds are transferred, "transfer pool funds" needs to be disabled

### ISSUE THREAD

**Issue by andydemeulemeester** [Safehaven-io/ThorBlock#27]
![image](https://user-images.githubusercontent.com/5653918/47459905-91e13580-d7dd-11e8-8fef-01d314dd1148.png)

**Comment by wijzijnwolf** [comment]
there are 2 similar states: "transferred" and "funds_transferred"

can someone clarify the difference?

(currently: the transfer pool funds section is hidden when state is "funds_transferred")

**Comment by wijzijnwolf** [comment]
changed: transfer pool funds is now only visible when state is "open"
