### ISSUE TITLE
Update Arkane logo on the homepage of Thorblock

### ISSUE THREAD

**Issue by karelstriegel** [Safehaven-io/ThorBlock#28]
Please use the following logo on the homepage.
![image](https://user-images.githubusercontent.com/6882032/47564433-4f2a7500-d925-11e8-88a4-22af3288a7a0.png)

The link behind the logo should be: https://arkane.network/?utm_source=thorblock&utm_medium=ref&utm_campaign=thirthparty&utm_content=thorblock_homepage

**Comment by wijzijnwolf** [comment]
fixed
