### ISSUE TITLE
Contribute to pool - can contribute less than the minimum

### ISSUE THREAD

**Issue by davy-vr** [Safehaven-io/ThorBlock#4]
It is possible to contribute to the pool (from the frontend) less than the pool minimum:
![image](https://user-images.githubusercontent.com/668625/47085845-2e249e80-d218-11e8-882e-7c8d4d8e0196.png)

**Comment by wijzijnwolf** [comment]
fixed on serverside (php) and clientside (js)

will set minimum to either the min per contributor threshold OR remaining pool allocation (if its less)

Please test this thoroughly on different browsers though (paying special attention to decimals/thousands)
