### ISSUE TITLE
Can contribute to a pool that is full / can contribute more to the pool than is left

### ISSUE THREAD

**Issue by davy-vr** [Safehaven-io/ThorBlock#6]
When a pool is full, it is still possible to contribute (user should see that pool is full)

additionally, when a user tries to contribute and there is only 6 VET available, the max amount that he can contribute should be 6

![image](https://user-images.githubusercontent.com/668625/47086400-a475d080-d219-11e8-88b7-58ef3825cb66.png)

**Comment by wijzijnwolf** [comment]
fixed on serverside (php) and clientside (js)

will set maximum to the remaining pool allocation.
