### ISSUE TITLE
Transfer pool funds should be disabled when no token address is present

### ISSUE THREAD

**Issue by davy-vr** [Safehaven-io/ThorBlock#8]
disable the button transfer pool funds when the token address is still 0x0000... but warn the user that he has to set this first

![image](https://user-images.githubusercontent.com/668625/47086738-a7bd8c00-d21a-11e8-8d2e-0c037026671e.png)

**Comment by wijzijnwolf** [comment]
fixed on serverside (php)

**Comment by JurgenSchouppe** [comment]
closed
