### ISSUE TITLE
When logged in using an existing Arkane account, it appears I'm not logged in when coming back to thorblock

### ISSUE THREAD

**Issue by karelstriegel** [Safehaven-io/ThorBlock#9]
When logged in using an existing Arkane account, it appears I'm not logged in when coming back to thorblock

![image](https://user-images.githubusercontent.com/6882032/47095337-58348b80-d22d-11e8-9792-4524391bfb1a.png)

**Comment by wijzijnwolf** [comment]
Removed state check (was only used internally).

Can try again?
